# Function for tabel formatting

In [22]:
def find_missing_numbers(input_str, start=0, end=31):
    """
    Finds missing numbers within a specified range from a comma-separated list.

    Parameters:
    - input_str (str): A string of numbers separated by commas.
    - start (int): The start of the range (inclusive).
    - end (int): The end of the range (inclusive).

    Returns:
    - List[int]: A sorted list of missing numbers.
    """
    # Step 1: Split the input string by commas and convert to integers
    try:
        # Remove any whitespace and convert each split item to integer
        numbers = [int(num.strip()) for num in input_str.split(',')]
    except ValueError:
        raise ValueError("Input must be a comma-separated list of integers.")

    # Step 2: Create a set of all numbers within the desired range
    full_set = set(range(start, end + 1))

    # Step 3: Convert the input list to a set to remove duplicates and for efficient lookup
    given_set = set(numbers)

    # Step 4: Identify missing numbers by set difference
    missing_numbers = sorted(full_set - given_set)

    return missing_numbers

# Example Usage

# Input: Comma-separated list of numbers (as a string)
input_numbers = "0, 2,5,8,9,16,19,20,26,31,1,3,4,6,7,10,12,15,17,18,21,22,24,25,27,28,30,21,33,34,35,13,23,29,11,14"

# Find missing numbers from 1 to 31
missing = find_missing_numbers(input_numbers, 0, 35)

# Display the result
print("Missing numbers from 1 to 31:", missing)

Missing numbers from 1 to 31: [32]

In [59]:
def style_dataframe(df, exclude_columns=['Cluster_Label']):
    """
    Styles the DataFrame by coloring cells with '+' as green and '-' as red.
    All other cells remain uncolored. The function excludes specified columns from styling.

    Parameters:
    - df (pd.DataFrame): The DataFrame to style.
    - exclude_columns (list): List of column names to exclude from styling.

    Returns:
    - pd.io.formats.style.Styler: The styled DataFrame.
    """
    
    # Define the cell highlighting function
    def highlight_cells(val):
        if val == '+':
            return 'background-color: lightgreen'
        elif val == '-':
            return 'background-color: lightcoral'
        else:
            return ''
    
    # Identify columns to style by excluding the specified columns
    cols_to_style = [col for col in df.columns if col not in exclude_columns]
    
    # Apply the highlighting function to the selected columns
    styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)
    
    # Enhance table aesthetics: center alignment and borders
    styled_df = styled_df.set_table_styles([
        {'selector': 'th', 
         'props': [('font-size', '12pt'), 
                   ('text-align', 'center'), 
                   ('border', '1px solid black')]},
        {'selector': 'td', 
         'props': [('text-align', 'center'), 
                   ('border', '1px solid black')]}
    ])
    
    return styled_df

In [60]:
import pandas as pd
import dataframe_image as dfi
from IPython.display import Image, display

In [39]:
import dataframe_image as dfi
from IPython.display import Image, display

def export_and_display_image(styled_df, export_path='styled_table.png'):
    """
    Exports the styled DataFrame as an image and displays it within the notebook.

    Parameters:
    - styled_df (pd.io.formats.style.Styler): The styled DataFrame to export.
    - export_path (str): File path to save the image (e.g., 'styled_table.png').
    - scale (int): Scale factor for the exported image resolution.

    Returns:
    - None
    """
    
    # Export the styled DataFrame as an image
    try:
        dfi.export(styled_df, export_path)
        print(f"Styled DataFrame exported successfully to {export_path}")
    except Exception as e:
        print("An error occurred while exporting the image:", e)
    
    # Display the exported image within the notebook
    try:
        display(Image(filename=export_path))
    except FileNotFoundError:
        print(f"The file {export_path} was not found. Please check the export path.")

# 4-ap data

In [41]:
vpa_ap_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/base_4ap_vpa/label/summary_of_statistical_tests.csv')
base_ap_styled = style_dataframe(vpa_ap_data)
base_ap_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

# Grouped PTZ Data

In [7]:
PTZ_grouped_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/PTZ_combined_reps_different_levels/label/summary_of_statistical_tests.csv')
PTZ_grouped_styled = style_dataframe(PTZ_grouped_data)
PTZ_grouped_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

# ND2 Data

In [61]:
nD2_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/4ap_base_nd2_nd2_edit/label/summary_of_statistical_tests.csv')
nD2_styled = style_dataframe(nD2_data)
nD2_styled

/tmp/ipykernel_638415/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

In [54]:
nD2_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/4ap_base_nd2_nd2_edit/velocist_8_clust/summary_of_statistical_tests.csv')

df=nD2_data

In [57]:
df=nD2_data

In [58]:
import itertools

# Define the comparison columns
comparison_columns = ['Baseline - ND2_5MM', 'Baseline - ND2_g20', 'ND2_5MM - ND2_g20']

# Replace NaN with '0' to indicate non-significant differences
df_filled = df[comparison_columns].fillna('0')

# Optional: Ensure that only '+', '-', and '0' are present
# If there are other symbols or numbers, map them accordingly
# For example, if '0' is represented as 0, convert it to string
df_filled = df_filled.replace({0: '0'})

# Generate all possible combinations of '+', '-', '0' for the three comparisons
signs = ['+', '-', '0']
all_combinations = list(itertools.product(signs, repeat=3))

# Create a DataFrame for all possible combinations
combinations_df = pd.DataFrame(all_combinations, columns=comparison_columns)

# Group the filled DataFrame by the comparison columns and count occurrences
counts = df_filled.groupby(comparison_columns).size().reset_index(name='Count')

# Merge with all possible combinations to include combinations with zero counts
summary_df = combinations_df.merge(counts, on=comparison_columns, how='left')

# Replace NaN counts with 0 and convert to integer
summary_df['Count'] = summary_df['Count'].fillna(0).astype(int)

# Optional: Sort the summary table for better readability
# For example, sort by Count descending
summary_df = summary_df.sort_values(by='Count', ascending=False).reset_index(drop=True)

# Display the summary table
print("\nSummary Table of Statistical Significance Patterns:")
print(summary_df)

Summary Table of Statistical Significance Patterns:
   Baseline - ND2_5MM Baseline - ND2_g20 ND2_5MM - ND2_g20  Count
0                   +                  +                 0     21
1                   0                  0                 0     10
2                   0                  +                 0      3
3                   +                  0                 0      2
4                   -                  0                 +      0
5                   0                  0                 -      0
6                   0                  0                 +      0
7                   0                  -                 0      0
8                   0                  -                 -      0
9                   0                  -                 +      0
10                  0                  +                 -      0
11                  0                  +                 +      0
12                  -                  0                 0      0
13                  -                  0                 -      0
14                  +                  +                 +      0
15                  -                  -                 0      0
16                  +                  +                 -      0
17                  -                  -                 +      0
18                  -                  +                 0      0
19                  -                  +                 -      0
20                  -                  +                 +      0
21                  +                  0                 -      0
22                  +                  0                 +      0
23                  +                  -                 0      0
24                  +                  -                 -      0
25                  +                  -                 +      0
26                  -                  -                 -      0

# All Seizure Agent

In [6]:
all_seizure_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/PTZ_vs_4-AP_vs_ND2/label/summary_of_statistical_tests.csv')
all_seizure_styled = style_dataframe(all_seizure_data)
all_seizure_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

# velocity Analysis

4ap

In [24]:
vpa_ap_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/base_4ap_vpa/velocist_8_clust/summary_of_statistical_tests.csv')
base_ap_styled = style_dataframe(vpa_ap_data)
base_ap_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

ptz

In [25]:
PTZ_grouped_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/PTZ_combined_reps_different_levels/velocist_8_clust/summary_of_statistical_tests.csv')
PTZ_grouped_styled = style_dataframe(PTZ_grouped_data)
PTZ_grouped_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

nd2

In [67]:
nD2_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/4ap_base_nd2_nd2_edit/velocist_8_clust/summary_of_statistical_tests.csv')
nD2_styled = style_dataframe(nD2_data)
nD2_styled

/tmp/ipykernel_638415/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

In [27]:
all_seizure_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/PTZ_vs_4-AP_vs_ND2/velocist_8_clust/summary_of_statistical_tests.csv')
all_seizure_styled = style_dataframe(all_seizure_data)
all_seizure_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

all agents

# agglom 7

4ap

In [28]:
vpa_ap_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/base_4ap_vpa/agglom_7/summary_of_statistical_tests.csv')
base_ap_styled = style_dataframe(vpa_ap_data)
base_ap_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

ptz

In [29]:
PTZ_grouped_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/PTZ_combined_reps_different_levels/agglom_7/summary_of_statistical_tests.csv')
PTZ_grouped_styled = style_dataframe(PTZ_grouped_data)
PTZ_grouped_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

nd2

In [30]:
nD2_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/4ap_base_nd2_nd2_edit/agglom_7/summary_of_statistical_tests.csv')
nD2_styled = style_dataframe(nD2_data)
nD2_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

all

In [31]:
all_seizure_data=pd.read_csv('/home/alexmatthews/tadpole_home_mount/velocity_analysis/sep_18_k_36/comparison_of_cluster_proportions/PTZ_vs_4-AP_vs_ND2/agglom_7/summary_of_statistical_tests.csv')
all_seizure_styled = style_dataframe(all_seizure_data)
all_seizure_styled

/tmp/ipykernel_385795/1833912052.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(highlight_cells, subset=cols_to_style)

# Analyse Bhevaioral Types

In [19]:
# Step 1: Import Necessary Libraries
import pandas as pd
from io import StringIO

# Step 2: Define the Tadpole Data as a Multi-line String
tadpole_markdown_table = """
| ID  | Tadpole description                                            | velocity description           | %     | Category qual      |
| --- | -------------------------------------------------------------- | ------------------------------ | ----- | ------------------ |
| 0   | undulatory  tail down tip up                                   | n                              | 3.75  | undulatory         |
| 1   | swipe up whole tail, EYES ROTATE ANTICLOCKWISE                 | N                              | 0.37  |                    |
| 2   | still                                                          | n                              | 52.05 | Still              |
| 3   | return from up c start                                         | 0.14 yaw                       | 0.03  | C-SC               |
| 4   | stationary, ==tail landmarks move forward? ==                  | n                              | 3.63  | Impact compression |
| 5   | undulatory 2 slight down, 3,4,tip up                           | n                              | 3.68  |                    |
| 6   | up cstart                                                      | -0.14 yaw                      | 0.05  | C-SC               |
| 7   | small tail swipe up from down                                  | small thrust                   | 0.59  |                    |
| 8   | big swipe up from down 2,3,tip and smaller on tail1            | n                              | 1.29  |                    |
| 9   | left (anticlockwise) saccade                                   | -1 yaw                         | 0.46  |                    |
| 10  | tail tightly spaced to big move - flip                         | 0.25 thrust                    | 0.23  | Flip               |
| 11  | seipe 2,3,tip down                                             | n                              | 3.2   |                    |
| 12  | stationary drift slightly up                                   | n                              | 4.13  | head bob           |
| 13  | swipe tail up big                                              | 0.15 thrust                    | 0.83  |                    |
| 14  | swipe up from down                                             |                                | 1.47  |                    |
| 15  | Huge slip and tail contract   ==down cstart at edge of plate== | -1 slip                        | 0.00  | Edge Case CSC      |
| 16  | swipe down from up                                             | n                              | 1.31  |                    |
| 17  | stationary with slight drift of markers smaller                | n                              | 1.68  | Impact OCompressio |
| 18  | stationary with slight drift of markers larger                 | n                              | 6.97  | Impact comptrssion |
| 19  | right (clockwise) saccade                                      | 0.99 yaw                       | 0.46  |                    |
| 20  | swipe whole tail down from up                                  | 0.2995 thrust                  | 0.29  |                    |
| 21  | tail back and up                                               | 0.20 thrust                    | 1.11  |                    |
| 22  | down cstart                                                    | n                              | 0.09  | C-SC               |
| 23  | big swipe tail up from down                                    | n                              | 0.17  | UTB                |
| 24  | ==return from down cstart? or big swipe up and flip  ==        | -1 thrust, 0.56 slip, 0.20 yaw | 0.00  | Edge Case CSC      |
| 25  | swipe up from down                                             | n                              | 0.32  | UTB                |
| 26  | swipe down from up                                             |                                | 1.11  |                    |
| 27  | small swipe down tail  from middle - gliding?                  | 0.17 thrust                    | 1.27  |                    |
| 28  | undulation down of tail 1,2,3 and tip stays up                 |                                | 2.57  | HEad bob           |
| 29  | big swipe up                                                   | 0.26 thrust, 0.13 slip         | 0.33  |                    |
| 30  | return from down cstart                                        |                                | 0.06  | C-SC               |
| 31  | undulatory tip down 1,2,3 up                                   |                                | 4.07  | undulatory         |
| 32  | big swipe down from up                                         |                                | 0.17  | UTB                |
| 33  | swipe down  from down                                          |                                | 0.68  |                    |
| 34  | swipe down from slightly up                                    |                                | 0.23  | UTB                |
| 35  | tail landmakrs move larger with glide                          | 0.2 thrust                     | 1.35  | Impact compressio  | 

"""

# Step 3: Load the Data into a Pandas DataFrame
tadpole_data_io = StringIO(tadpole_markdown_table)

try:
    tadpole_dataframe = pd.read_csv(
        tadpole_data_io,
        sep='|',
        skipinitialspace=True,
        skiprows=[1,2],
        engine='python'
    )
except Exception as e:
    print("Error reading the CSV data:", e)
    raise

# Step 4: Clean the DataFrame
tadpole_dataframe = tadpole_dataframe.iloc[:, 1:-1]
tadpole_dataframe.columns = tadpole_dataframe.columns.str.strip()

# Debugging: Inspect the DataFrame before conversion
print("DataFrame after initial cleanup:")
display(tadpole_dataframe.head())

print("\nData types of each column:")
print(tadpole_dataframe.dtypes)

print("\nUnique values in 'ID' column:")
print(tadpole_dataframe['ID'].unique())

# Step 5: Convert the 'ID' Column to Integer Type
tadpole_dataframe['ID'] = tadpole_dataframe['ID'].astype(str).str.strip()

try:
    tadpole_dataframe['ID'] = tadpole_dataframe['ID'].astype(int)
except ValueError as ve:
    print("Error converting 'ID' column to int:", ve)
    non_convertible = tadpole_dataframe[~tadpole_dataframe['ID'].astype(str).str.strip().str.isdigit()]
    print("\nNon-convertible 'ID' values:")
    print(non_convertible['ID'])
    raise

# Verify the conversion
print("\nComplete Tadpole DataFrame after 'ID' conversion:")
display(tadpole_dataframe.head())

# Step 8: Define a Reusable Function for Filtering
def filter_tadpole_clusters(dataframe, cluster_id_list):
    """
    Filters the tadpole DataFrame based on a list of cluster IDs.

    Parameters:
    - dataframe (pd.DataFrame): The original tadpole DataFrame.
    - cluster_id_list (list): List of cluster IDs to filter.

    Returns:
    - pd.DataFrame: Filtered DataFrame containing only the specified clusters.
    """
    return dataframe[dataframe['ID'].isin(cluster_id_list)].reset_index(drop=True)
# Usage Example of the Function
pd.set_option('display.max_colwidth', None)  # Remove column width limit
pd.set_option('display.max_columns', None)   # Display all columns
pd.set_option('display.width', None)         # Allow unlimited width

DataFrame after initial cleanup:

,ID,Tadpole description,velocity description,%,Category qual
0,0,undulatory tail down tip up,n,3.75,undulatory
1,1,"swipe up whole tail, EYES ROTATE ANTICLOCKWISE",N,0.37,NaN
2,2,still,n,52.05,Still
3,3,return from up c start,0.14 yaw,0.03,C-SC
4,4,"stationary, ==tail landmarks move forward? ==",n,3.63,Impact compression

Data types of each column:
ID                        int64
Tadpole description      object
velocity description     object
%                       float64
Category qual            object
dtype: object

Unique values in 'ID' column:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]

Complete Tadpole DataFrame after 'ID' conversion:

,ID,Tadpole description,velocity description,%,Category qual
0,0,undulatory tail down tip up,n,3.75,undulatory
1,1,"swipe up whole tail, EYES ROTATE ANTICLOCKWISE",N,0.37,NaN
2,2,still,n,52.05,Still
3,3,return from up c start,0.14 yaw,0.03,C-SC
4,4,"stationary, ==tail landmarks move forward? ==",n,3.63,Impact compression

## 4-AP

### Unchanged

In [21]:

new_cluster_ids = [0,5,8,15,16,44,26,31,11,24]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,0,undulatory tail down tip up,n,3.75,undulatory
1,5,"undulatory 2 slight down, 3,4,tip up",n,3.68,NaN
2,8,"big swipe up from down 2,3,tip and smaller on tail1",n,1.29,NaN
3,11,"seipe 2,3,tip down",n,3.20,NaN
4,15,Huge slip and tail contract ==down cstart at edge of plate==,-1 slip,0.00,Edge Case CSC
5,16,swipe down from up,n,1.31,NaN
6,24,==return from down cstart? or big swipe up and flip ==,"-1 thrust, 0.56 slip, 0.20 yaw",0.00,Edge Case CSC
7,26,swipe down from up,NaN,1.11,NaN
8,31,"undulatory tip down 1,2,3 up",NaN,4.07,undulatory

### Changed and rescued fully

In [22]:

new_cluster_ids = [29, 13,20]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,13,swipe tail up big,0.15 thrust,0.83,NaN
1,20,swipe whole tail down from up,0.2995 thrust,0.29,NaN
2,29,big swipe up,"0.26 thrust, 0.13 slip",0.33,NaN

# Resuced partially

In [24]:

new_cluster_ids = [3,4,10,21, 22,25,30,34,35,2]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,2,still,n,52.05,Still
1,3,return from up c start,0.14 yaw,0.03,C-SC
2,4,"stationary, ==tail landmarks move forward? ==",n,3.63,Impact compression
3,10,tail tightly spaced to big move - flip,0.25 thrust,0.23,Flip
4,21,tail back and up,0.20 thrust,1.11,NaN
5,22,down cstart,n,0.09,C-SC
6,25,swipe up from down,n,0.32,UTB
7,30,return from down cstart,NaN,0.06,C-SC
8,34,swipe down from slightly up,NaN,0.23,UTB
9,35,tail landmakrs move larger with glide,0.2 thrust,1.35,Impact compressio

## not recovered

In [25]:
new_cluster_ids = [6,7,12,14,1,17,18,27,28,33]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,1,"swipe up whole tail, EYES ROTATE ANTICLOCKWISE",N,0.37,NaN
1,6,up cstart,-0.14 yaw,0.05,C-SC
2,7,small tail swipe up from down,small thrust,0.59,NaN
3,12,stationary drift slightly up,n,4.13,head bob
4,14,swipe up from down,NaN,1.47,NaN
5,17,stationary with slight drift of markers smaller,n,1.68,Impact OCompressio
6,18,stationary with slight drift of markers larger,n,6.97,Impact comptrssion
7,27,small swipe down tail from middle - gliding?,0.17 thrust,1.27,NaN
8,28,"undulation down of tail 1,2,3 and tip stays up",NaN,2.57,HEad bob
9,33,swipe down from down,NaN,0.68,NaN

# PTZ

Increase at 1MM

In [32]:
new_cluster_ids = [3, 6,7,10,21,22,25,27,33,35]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,3,return from up c start,0.14 yaw,0.03,C-SC
1,6,up cstart,-0.14 yaw,0.05,C-SC
2,7,small tail swipe up from down,small thrust,0.59,NaN
3,10,tail tightly spaced to big move - flip,0.25 thrust,0.23,Flip
4,21,tail back and up,0.20 thrust,1.11,NaN
5,22,down cstart,n,0.09,C-SC
6,25,swipe up from down,n,0.32,UTB
7,27,small swipe down tail from middle - gliding?,0.17 thrust,1.27,NaN
8,33,swipe down from down,NaN,0.68,NaN
9,35,tail landmakrs move larger with glide,0.2 thrust,1.35,Impact compressio

Increase above baslien in 3,6,10

In [34]:
new_cluster_ids = [4,9,12,13,14,16,17,18,19,20,23,26,28,29,30,23,34]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,4,"stationary, ==tail landmarks move forward? ==",n,3.63,Impact compression
1,9,left (anticlockwise) saccade,-1 yaw,0.46,NaN
2,12,stationary drift slightly up,n,4.13,head bob
3,13,swipe tail up big,0.15 thrust,0.83,NaN
4,14,swipe up from down,NaN,1.47,NaN
5,16,swipe down from up,n,1.31,NaN
6,17,stationary with slight drift of markers smaller,n,1.68,Impact OCompressio
7,18,stationary with slight drift of markers larger,n,6.97,Impact comptrssion
8,19,right (clockwise) saccade,0.99 yaw,0.46,NaN
9,20,swipe whole tail down from up,0.2995 thrust,0.29,NaN
10,23,big swipe tail up from down,n,0.17,UTB
11,26,swipe down from up,NaN,1.11,NaN
12,28,"undulation down of tail 1,2,3 and tip stays up",NaN,2.57,HEad bob
13,29,big swipe up,"0.26 thrust, 0.13 slip",0.33,NaN
14,30,return from down cstart,NaN,0.06,C-SC
15,34,swipe down from slightly up,NaN,0.23,UTB

Behaviors that dont incease actross 3,6,10

In [36]:
new_cluster_ids = [5,8,11,15,24,31]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,5,"undulatory 2 slight down, 3,4,tip up",n,3.68,NaN
1,8,"big swipe up from down 2,3,tip and smaller on tail1",n,1.29,NaN
2,11,"seipe 2,3,tip down",n,3.20,NaN
3,15,Huge slip and tail contract ==down cstart at edge of plate==,-1 slip,0.00,Edge Case CSC
4,24,==return from down cstart? or big swipe up and flip ==,"-1 thrust, 0.56 slip, 0.20 yaw",0.00,Edge Case CSC
5,31,"undulatory tip down 1,2,3 up",NaN,4.07,undulatory

increase u shape for 3

In [29]:
new_cluster_ids = [0,5,11,31
]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,0,undulatory tail down tip up,n,3.75,undulatory
1,5,"undulatory 2 slight down, 3,4,tip up",n,3.68,NaN
2,11,"seipe 2,3,tip down",n,3.20,NaN
3,31,"undulatory tip down 1,2,3 up",NaN,4.07,undulatory

# Comparion PTZ 4AP

In [38]:
new_cluster_ids = [4,12,18,28]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,4,"stationary, ==tail landmarks move forward? ==",n,3.63,Impact compression
1,12,stationary drift slightly up,n,4.13,head bob
2,18,stationary with slight drift of markers larger,n,6.97,Impact comptrssion
3,28,"undulation down of tail 1,2,3 and tip stays up",NaN,2.57,HEad bob

3MM PTZ more than 4aAP

In [37]:
5,8,9,11,13,16,23,26,32 new_cluster_ids = []  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,5,"undulatory 2 slight down, 3,4,tip up",n,3.68,NaN
1,8,"big swipe up from down 2,3,tip and smaller on tail1",n,1.29,NaN
2,9,left (anticlockwise) saccade,-1 yaw,0.46,NaN
3,11,"seipe 2,3,tip down",n,3.20,NaN
4,13,swipe tail up big,0.15 thrust,0.83,NaN
5,16,swipe down from up,n,1.31,NaN
6,23,big swipe tail up from down,n,0.17,UTB
7,26,swipe down from up,NaN,1.11,NaN
8,32,big swipe down from up,NaN,0.17,UTB

In [ ]:
new_cluster_ids = [3,4,10,21, 22,25,30,34,35,2]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

ND2 and g20 over base

In [62]:
new_cluster_ids = [32, 33,34,35,24,25,30,28,27,21,22,17,18,15,12,10,6,7,3,4,1]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,1,"swipe up whole tail, EYES ROTATE ANTICLOCKWISE",N,0.37,NaN
1,3,return from up c start,0.14 yaw,0.03,C-SC
2,4,"stationary, ==tail landmarks move forward? ==",n,3.63,Impact compression
3,6,up cstart,-0.14 yaw,0.05,C-SC
4,7,small tail swipe up from down,small thrust,0.59,NaN
5,10,tail tightly spaced to big move - flip,0.25 thrust,0.23,Flip
6,12,stationary drift slightly up,n,4.13,head bob
7,15,Huge slip and tail contract ==down cstart at edge of plate==,-1 slip,0.00,Edge Case CSC
8,17,stationary with slight drift of markers smaller,n,1.68,Impact OCompressio
9,18,stationary with slight drift of markers larger,n,6.97,Impact comptrssion
10,21,tail back and up,0.20 thrust,1.11,NaN
11,22,down cstart,n,0.09,C-SC
12,24,==return from down cstart? or big swipe up and flip ==,"-1 thrust, 0.56 slip, 0.20 yaw",0.00,Edge Case CSC
13,25,swipe up from down,n,0.32,UTB
14,27,small swipe down tail from middle - gliding?,0.17 thrust,1.27,NaN
15,28,"undulation down of tail 1,2,3 and tip stays up",NaN,2.57,HEad bob
16,30,return from down cstart,NaN,0.06,C-SC
17,32,big swipe down from up,NaN,0.17,UTB
18,33,swipe down from down,NaN,0.68,NaN
19,34,swipe down from slightly up,NaN,0.23,UTB
20,35,tail landmakrs move larger with glide,0.2 thrust,1.35,Impact compressio

just 5MM

In [64]:
new_cluster_ids = [11,14]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,11,"seipe 2,3,tip down",n,3.20,NaN
1,14,swipe up from down,NaN,1.47,NaN

just g20

In [65]:
new_cluster_ids = [13,23,29]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,13,swipe tail up big,0.15 thrust,0.83,NaN
1,23,big swipe tail up from down,n,0.17,UTB
2,29,big swipe up,"0.26 thrust, 0.13 slip",0.33,NaN

nio change

In [66]:
new_cluster_ids = [0,16,19,2,20,26,31,5,8,9]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

# 5MM and g20 over baslien: 


# 32, 33,34,35,24,25,30,28,27,21,22,17,18,15,12,10,6,7,3,4,1 All behvaior types but undulatory swimming 
# - csc , flip edge case csc impact compresssion head bob 

# just 5 MM

# 11,14 recular swimmign behaviours 

# just g20over basline 
# 13,23,29 UTB and regualr swimmign behaviours 



# no change 
# 0,16,19,2,20,26,31,5,8,9 - undulartory and regular swimmign behaviours 


# tallk about initial test - not significant
#  anhtihing


#  we did s ee some partial changes that wer edifferent between the base and not
# give sets of statistically different relationships, and explainw hat behaviors werein each type wise




# give graphs to show each relationshi 





# - these are just a lot more subtle in hbehavior -
# this is expected
display(new_filtered_clusters)

,ID,Tadpole description,velocity description,%,Category qual
0,0,undulatory tail down tip up,n,3.75,undulatory
1,2,still,n,52.05,Still
2,5,"undulatory 2 slight down, 3,4,tip up",n,3.68,NaN
3,8,"big swipe up from down 2,3,tip and smaller on tail1",n,1.29,NaN
4,9,left (anticlockwise) saccade,-1 yaw,0.46,NaN
5,16,swipe down from up,n,1.31,NaN
6,19,right (clockwise) saccade,0.99 yaw,0.46,NaN
7,20,swipe whole tail down from up,0.2995 thrust,0.29,NaN
8,26,swipe down from up,NaN,1.11,NaN
9,31,"undulatory tip down 1,2,3 up",NaN,4.07,undulatory

In [ ]:
new_cluster_ids = [3,4,10,21, 22,25,30,34,35,2]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)

In [ ]:
new_cluster_ids = [3,4,10,21, 22,25,30,34,35,2]  # Replace as needed

new_filtered_clusters = filter_tadpole_clusters(tadpole_dataframe, new_cluster_ids)

display(new_filtered_clusters)